inherit_mode:
  merge:
    - Include
    - Exclude

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7.1

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/LineLength:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Naming/PredicateName:
  ForbiddenPrefixes:
    - is_
    - have_

# `described_class` makes tests harder to read. When using tools that allow
# jumping between definitions and the respective tests in a Rails project, or
# using global search, the class `described_class` refers to might not be clear
# to the reader. By avoiding the shortcut, we make sure the test stands on its
# own with as much information as possible.
RSpec/DescribedClass:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
